### ISSUE TITLE
Two suggestions: screenshots, and table-of-features

### ISSUE THREAD

**Issue by rubyFeedback** [Osiris-Team/Headless-Browser#1]
I suggest two things:

(1) add screenshots, no matter how incomplete it is so far, ideally of some simple website, and then perhaps also at some later point a more complicated web site

(2) for attracting devs, I'd recommend a table of implemented (and missing) features. That way people can quickly look at what needs work and can invest a little bit of time perhaps when they see amount of work required for this or that feature

Just two suggestions! Please feel free to ignore this or close it at any moment in time for any reason.

**Comment by Osiris-Team** [comment]
Yep already was thinking of this. Added the todo list. At the moment there is nothing you can take screenshots of, except raw html code.
